spring:
  application:
    name: timesheet-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 5200
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
